[package]
name = "jarvis-kernel"
version = "0.1.0"
edition = "2021"
authors = ["JARVIS Project"]

[dependencies]
bootloader_api = "0.11"
spinning_top = "0.3.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
font8x8 = "0.3.1"
x86_64 = "0.14.2"
linked_list_allocator = "0.10.1"
uart_16550 = "0.3.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
