[package]
name = "jarvis-kernel"
version = "0.1.0"
edition = "2021"
resolver = "2"
authors = ["JARVIS Project"]

[[bin]]
name = "jarvis-kernel"
test = false
harness = false

[dependencies]
bootloader_api = { version = "0.11.11", default-features = false }
serde = { version = "1.0", default-features = false }
spinning_top = "0.3.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
font8x8 = { version = "0.3.1", default-features = false, features = ["unicode"] }
x86_64 = "0.14.2"
linked_list_allocator = "0.10.1"
uart_16550 = "0.3.0"
crossbeam-queue = { version = "0.3.8", default-features = false, features = ["alloc"] }
conquer-once = { version = "0.2.0", default-features = false }
futures-util = { version = "0.3.28", default-features = false, features = ["alloc"] }
pc-keyboard = "0.7.0"
pic8259 = "0.10.1"

[target.'cfg(not(target_os = "none"))'.dependencies]
bootloader = "0.11"

[dev-dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
