services:
  jarvis-os:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jarvis_vm
    devices:
      - /dev/kvm
    ports:
      - "8080:8080" # noVNC Web Interface
    volumes:
      - ../target/image/jarvis-os.img:/app/jarvis-os.img:ro
    restart: unless-stopped
